# .github/workflows/ci.yml
name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/requirements.txt
        pip install pytest flake8
        
    - name: Verify dataset exists
      run: |
        echo " Verificando dataset..."
        if [ -f "heart.csv" ]; then
          echo " Dataset encontrado"
          python -c "import pandas as pd; df = pd.read_csv('heart.csv'); print(f'游늵 Dataset shape: {df.shape}')"
        else
          echo " Dataset no encontrado"
          exit 1
        fi
        
    - name: Test model loading
      run: |
        echo " Probando carga del modelo..."
        python -c "
        import joblib
        try:
            model = joblib.load('app/model.joblib')
            print(' Modelo cargado correctamente')
            print(f' Tipo: {type(model)}')
            
            # Probar predicci칩n b치sica
            if hasattr(model, 'predict_proba'):
                print(' Modelo puede hacer predicciones')
            else:
                print('  Modelo no tiene predict_proba')
                
        except Exception as e:
            print(f' Error cargando modelo: {e}')
            exit(1)
        "
        
    - name: Run basic linting
      run: |
        echo " Ejecutando linting b치sico..."
        python -c "
        import ast
        # Verificar sintaxis de archivos Python
        files = ['app/api_flask.py', 'app/demo_standalone.py']
        for file in files:
            try:
                with open(file, 'r') as f:
                    ast.parse(f.read())
                print(f' {file} - Sintaxis correcta')
            except Exception as e:
                print(f' {file} - Error sintaxis: {e}')
        "

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - name: Build Docker image
      run: |
        echo " Construyendo imagen Docker..."
        docker build -t heart-api-flask -f docker/Dockerfile .
        
    - name: Verify Docker image
      run: |
        echo " Verificando imagen construida..."
        docker images heart-api-flask
        echo " Imagen Docker construida exitosamente"
        
    - name: Test Docker image
      run: |
        echo " Probando imagen Docker..."
        docker run -d --name test-container -p 5000:5000 heart-api-flask
        sleep 10
        echo " Contenedor iniciado"
        docker stop test-container
        docker rm test-container

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Basic security checks
      run: |
        echo " Ejecutando chequeos de seguridad b치sicos..."
        # Verificar que no hay archivos sensibles
        if [ ! -f "app/model.joblib" ]; then
          echo "  Modelo no incluido en repo (esto es normal para CI)"
        fi
        
        # Verificar requirements.txt
        if [ -f "docker/requirements.txt" ]; then
          echo " requirements.txt encontrado"
          cat docker/requirements.txt
        fi